# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLdzomDFlK7lupPEF5_eZ7wCYqk3NyOn
"""

import numpy as np

a = np.array([1,2,3]) #1D array
b = np.array([[1,2],[3,4]]) #2D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3D array
d = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])

print("1D array: ")
print(a)
print("2D array: ")
print(b)
print("3D array: ")
print(c)
print("4D array:")
print(d)
print("shape of 1D array:",a.shape)
print("shape of 2D array:",b.shape)
print("shape of 3D array:",c.shape)
print("shape of 4D array:",d.shape)
print("Number of dimensions of 1D array",a.ndim)
print("Number of dimensions of 2D array",b.ndim)
print("Number of dimensions of 3D array",c.ndim)
print("Number of dimensions of 4D array",d.ndim)

import numpy as np

sales_data = np.array([
    [100,200,150,300],
    [50,100,75,125],
    [200,150,300,250],
    [140,170,180,330],
    [150,160,190,340],
    [160,150,200,350],
    [170,140,210,360]

])

print("shape:",sales_data.shape)

sales_data[2]

sales_data[sales_data > 300]

weekend_sales_product4 = sales_data[[5,6], 3]
print(weekend_sales_product4)

#brodcasting
a = np.array([1,2,3])
b = 2
print(a+b)

#user case: you want to apply a 10% discount ro the sales of all products on day 1.
day_1_sales = sales_data[0]
print(day_1_sales)
discounted_sales = day_1_sales * 0.9
print(discounted_sales)

from numpy import *
a=zeros(5, int)
print(a)
a=zeros([2,3])
print(a)

a=array([12,45,67,77,22])
print(sqrt(a))
print(sin(a))
print(cos(a))
print(log(a))
print(sum(a))
print(min(a))
print(max(a))
print(sort(a))

from numpy import *
a=zeros([2,5], int)
print(a)

#numpy, linspace
a=linspace(1,10,5)
print(a)
a=linspace(0,10)
print(a)
b=a[[2,5],3]
print(b)

a=logspace(1,4,10)
print(a)

import numpy as np


array = np.arange(-10, 10).reshape(4, 5)


print("Array:", array)


average = np.mean(array)
print("Average of elements:", average)


num_elements = array.size
print("Number of elements:", num_elements)

below_zero = array[array < 0]
print("Elements below zero:", below_zero)