# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5qVG4WboJJt8deCMhSa5o3QMKdutO1l
"""

import matplotlib.pyplot as plt
days = ['mon','tue','wed','thu','fri']
attendance = [90,85,88,92,87]

plt.plot(days, attendance, marker='o', linestyle='-', color='purple')
plt.title('Class Attendance over a week')
plt.xlabel('Days')
plt.ylabel('number of students')
plt.grid(True)
plt.show()

subjects = ['math', 'science', 'english', 'history', 'geography']
scores = [90, 85, 78, 92, 88]

plt.bar(days, attendance, color='purple')
plt.title('Class Attendance over a week')
plt.xlabel('Days')
plt.ylabel('number of students')
plt.grid(True)
plt.show()

activities = ['sleep','school','homework','play','others']
hours = [8,6,3,4,3]

plt.pie(hours, labels=activities, autopct='%1.1f%%', startangle=90)
plt.title('daily time allocation')
plt.axis('equal')
plt.legend(bbox_to_anchor=(1,1))
plt.show()

study_hours = [1,2,3,4,5,6,7,8]
exam_scores = [40,50,55,65,70,80,85,90]

plt.scatter(study_hours, exam_scores, color='purple', marker='o')
plt.title('Study Hours vs Exam Scores')
plt.xlabel('Study Hours')
plt.ylabel('Exam Scores')
plt.grid(True)
plt.show()

ages = [18,19,18,20,21,19,20,18,22,21,20,19,20]
plt.hist(ages, bins=5, color='lightgreen', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

import seaborn as sns

print(sns.get_dataset_names())

tips = sns.load_dataset('tips')

print(tips.head())

print(tips.head())

print(tips)